package hranilec.gesel;

import javax.swing.JOptionPane;

/**
 *
 * @author Jonas Lasan
 */
public class PrijavaOkno extends javax.swing.JFrame {

    /**
     * Creates new form Prijava
     */
    public PrijavaOkno() {
        initComponents();
    }

    public void setVisible(boolean b)
    {
        super.setVisible(b);
        
        init();
    }
    
    public void init()
    {
        if (UpravljalecGesla.obstajaGeslo())
        {
            gumbPreveriGeslo.setText("Login");   
            gumbIzbrisiRacun.setVisible(true);
        }
        else
        {
            gumbPreveriGeslo.setText("Create profile"); 
            gumbIzbrisiRacun.setVisible(false);
        }
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        naslovNapis = new javax.swing.JLabel();
        gesloNapis = new javax.swing.JLabel();
        gumbPreveriGeslo = new javax.swing.JButton();
        gesloPolje = new javax.swing.JPasswordField();
        gumbIzbrisiRacun = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        naslovNapis.setFont(new java.awt.Font("Verdana", 0, 24)); // NOI18N
        naslovNapis.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        naslovNapis.setText("Password manager");

        gesloNapis.setText("Password");

        gumbPreveriGeslo.setText("Create password");
        gumbPreveriGeslo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                gumbPreveriGesloActionPerformed(evt);
            }
        });

        gumbIzbrisiRacun.setText("Delete profile");
        gumbIzbrisiRacun.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                gumbIzbrisiRacunActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(naslovNapis, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(gesloNapis, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(gumbIzbrisiRacun, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 28, Short.MAX_VALUE)
                        .addComponent(gumbPreveriGeslo, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(gesloPolje))
                .addGap(58, 58, 58))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(naslovNapis, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(gesloNapis)
                    .addComponent(gesloPolje, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(gumbPreveriGeslo)
                    .addComponent(gumbIzbrisiRacun))
                .addContainerGap(38, Short.MAX_VALUE))
        );

        naslovNapis.getAccessibleContext().setAccessibleName("naslovLabel");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void gumbPreveriGesloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_gumbPreveriGesloActionPerformed
        String geslo = new String(gesloPolje.getPassword());
        
        if (geslo.length() < 5)
        {
            JOptionPane.showMessageDialog(this, "Password must be at least 5 characters long!", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }
        
        if (UpravljalecGesla.obstajaGeslo())
        {
            boolean pravilno = UpravljalecGesla.preveriGeslo(geslo);
            if (pravilno)
            {
                GlobalniPodatki.kljuc = geslo;
                
                UpravljalecOken.skrijVse();
                UpravljalecOken.prikazi("osnovno");
            }
            else
            {
                JOptionPane.showMessageDialog(this, "Passwords do not match", "Wrong password!", JOptionPane.ERROR_MESSAGE);
            }
        }
        else
        {
            UpravljalecGesla.ustvariGeslo(geslo);   
            GlobalniPodatki.kljuc = geslo;
            
            UpravljalecOken.skrijVse();
            UpravljalecOken.prikazi("osnovno");
        }
        
        // Ponastavimo polje za vnos gesla
        gesloPolje.setText("");
        gesloPolje.requestFocus();
    }//GEN-LAST:event_gumbPreveriGesloActionPerformed

    private void gumbIzbrisiRacunActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_gumbIzbrisiRacunActionPerformed
        // TODO add your handling code here:
        
        LokalniPodatkovniUpravljalec.izbrisiDatoteko("./vnosi");
        LokalniPodatkovniUpravljalec.izbrisiDatoteko("./geslo");
        
        init();
    }//GEN-LAST:event_gumbIzbrisiRacunActionPerformed

    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PrijavaOkno.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PrijavaOkno.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PrijavaOkno.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PrijavaOkno.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PrijavaOkno().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel gesloNapis;
    private javax.swing.JPasswordField gesloPolje;
    private javax.swing.JButton gumbIzbrisiRacun;
    private javax.swing.JButton gumbPreveriGeslo;
    private javax.swing.JLabel naslovNapis;
    // End of variables declaration//GEN-END:variables
}
